"""empty message

Revision ID: 0bc2d8bdf458
Revises: ef0acfa68644
Create Date: 2019-03-02 18:17:25.558597

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0bc2d8bdf458'
down_revision = 'ef0acfa68644'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'call', 'caller', ['callee'], ['caller'])
    op.create_foreign_key(None, 'call', 'caller', ['caller'], ['caller'])
    op.create_foreign_key(None, 'question', 'user', ['author'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'question', type_='foreignkey')
    op.drop_constraint(None, 'call', type_='foreignkey')
    op.drop_constraint(None, 'call', type_='foreignkey')
    # ### end Alembic commands ###
