"""empty message

Revision ID: 3da6cff7d962
Revises: 
Create Date: 2019-09-14 11:44:15.435808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3da6cff7d962'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('active', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('anonymous', sa.Boolean(), nullable=True))
    op.add_column('user', sa.Column('authenticated', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'authenticated')
    op.drop_column('user', 'anonymous')
    op.drop_column('user', 'active')
    # ### end Alembic commands ###
