"""empty message

Revision ID: 88a140511afd
Revises: 
Create Date: 2019-03-10 16:55:32.011250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88a140511afd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caller',
    sa.Column('caller', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=256), nullable=True),
    sa.Column('code', sa.String(length=128), nullable=True),
    sa.Column('email', sa.String(length=132), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('caller')
    )
    op.create_index(op.f('ix_caller_full_name'), 'caller', ['full_name'], unique=True)
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('question',
    sa.Column('question', sa.Integer(), nullable=False),
    sa.Column('text', sa.String(length=255), nullable=False),
    sa.Column('author', sa.Integer(), nullable=True),
    sa.Column('valid', sa.Boolean(), nullable=True),
    sa.Column('date_added', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['author'], ['user.id'], ),
    sa.PrimaryKeyConstraint('question')
    )
    op.create_table('call',
    sa.Column('call', sa.Integer(), nullable=False),
    sa.Column('caller', sa.Integer(), nullable=True),
    sa.Column('callee', sa.Integer(), nullable=True),
    sa.Column('question', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('block', sa.Boolean(), nullable=True),
    sa.Column('assign_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['callee'], ['caller.caller'], ),
    sa.ForeignKeyConstraint(['caller'], ['caller.caller'], ),
    sa.ForeignKeyConstraint(['question'], ['question.question'], ),
    sa.PrimaryKeyConstraint('call')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('call')
    op.drop_table('question')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_index(op.f('ix_caller_full_name'), table_name='caller')
    op.drop_table('caller')
    # ### end Alembic commands ###
