"""empty message

Revision ID: 4001f23244dc
Revises: bd09271a1b3c
Create Date: 2019-03-04 21:47:19.575546

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4001f23244dc'
down_revision = 'bd09271a1b3c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('call', sa.Column('question', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'call', 'question', ['question'], ['question'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'call', type_='foreignkey')
    op.drop_column('call', 'question')
    # ### end Alembic commands ###
